export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE'

export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION'
export const CLEAR_ACTIVE_SECTION = 'CLEAR_ACTIVE_SECTION'

export const SET_EXPERIENCES = 'SET_EXPERIENCES'